theme = "adwaita-dark"

[editor]
bufferline = "multiple"
line-number = "relative"
rulers = [101]
true-color = true
indent-guides.render = true

[editor.cursor-shape]
insert = "bar"

[editor.lsp]
display-inlay-hints = true
display-messages = true

[keys.normal]
esc = ["collapse_selection", "keep_primary_selection"]
C-h = "jump_view_left"
C-j = "jump_view_down"
C-k = "jump_view_up"
C-l = "jump_view_right"
H = "goto_previous_buffer"
L = "goto_next_buffer"

[keys.normal.space]
w = ":write"
W = ":write-quit"
q = ":quit"
Q = ":quit!"
c = ":buffer-close"
'\' = ":hsplit"
'|' = ":vsplit"

[keys.normal.'\']
# send selection to tmux pane on the right
t = [''':pipe-to tmux load-buffer - \; paste-buffer -dpr -t '{right-of}' \; send-keys -t '{right-of}' Enter''']

# send selection to wezterm pane $HELIX_TARGET (export this env variable before)
w = [''':pipe-to wezterm cli send-text --pane-id $HELIX_TARGET''', ''':sh wezterm cli send-text --no-paste --pane-id $HELIX_TARGET $'\r'''']

[keys.normal.'\'.'\']
# send cell to tmux pane on the right
't' = [''':sh tmux send-keys Q/# Space %% Enter O# Escape Escape Nvg.a BSpace BSpace Escape Escape \\ t uuQ''']

# send cell to wezterm pane $HELIX_TARGET
'w' = [''':sh wezterm cli send-text --no-paste $'Q/# %%\r\rO#\e\eNvg.a\b\b\e\e\\wuuQ'''']
