theme = "adwaita-dark"

[editor]
bufferline = "multiple"
line-number = "relative"
rulers = [101]

[editor.cursor-shape]
insert = "bar"

[editor.lsp]
display-inlay-hints = true
display-messages = true

[keys.normal]
esc = ["collapse_selection", "keep_primary_selection"]
C-h = "jump_view_left"
C-j = "jump_view_down"
C-k = "jump_view_up"
C-l = "jump_view_right"
H = "goto_previous_buffer"
L = "goto_next_buffer"

[keys.normal.space]
w = ":write"
q = ":quit"
